spring.application.name=appmedic
#
spring.datasource.url=jdbc:postgresql://localhost:5432/appmedic
spring.datasource.username=postgres
spring.datasource.password=@Jose2007
#
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
logging.level.springframework.web=DEBUG